apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      name: helloworld-go-simple-response
    spec:
      containers:
        - image: <REGISTRY>/<NAMESPACE>/helloworld-go:1
          env:
            - name: TARGET
              value: "Go Sample v1"
